travis:
  secure:
    BINSTAR_TOKEN: n+EyTISNk7gir3g4/3ev9nXh7cgyc8uEqN3kLLBbSTNmpL3TsDJNSCS5XiQHiBByGYs9JOwwYRs59Ptq/jNNUhIwhNx9D+5RL4hACQp8P48wvTP21/PoFavkl2dKY8fmcRdspmhcrGgSxyMWZNeMXTisg0f96vCTNiHBnupJ4s9uGp/RQ1ygt0wPZ/vTwSpzDl+YUieTDhenKlcRtGMfYfLhud6Tf/eR7mWfd6DS3NGJvVfpIfptwbUaXXfF+bVnKhunjF1S9i5l/pc/EMXEC3sr6WhXLXGQ7xqLPyK8pXrif8ddG9HD3xMnAJA27F732VxYqW49HH+9ihkN992I9L5VOzCiHI1yRf82snzaxhBNJTH4ejveQVsrgoZsrSN6n6sn1ORd8n0qrlONPJiaeG2f20ym56r/s3OCoklM/osmGTRd8XAe9HQV4G3/y6K47xDgeFfvVi6mvOeOg/bOA/rgiu121JdjoSXOKL3Pmw44RRj+tRYk4ItZmspE0E/NTe1B0Tcj6m1r2TWcXalm67EtyexBPUJA+UlX9V5W5sJh4KRHQo0ZfLiiCQ4Q74zxPFRLcRJIH0WVk0rjCsFRLKqLfE9CKS11vlkuiwd8P5MOITt3WyaW3OdIqEPAz0DirZXsUd8AkYjjk07IwVL/C5sPpzv1By0mMWoT2Tat/Es=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
