travis:
  secure:
    BINSTAR_TOKEN: lzI8eWBLCtuUB8THK3B+1Cd2zXoFiEIwgKImp33na8fkhB3GiGkg4Ik+q6lXj8TFSDFO4RQa6BPrevP99/kBEgb27wbIUPU067gIBHK+37PLmbf4OU0ZrUkwE6s0EijbEgdSITPbQnFYX8+LpIOBs0BAyAqDk/t11L+J0EeHpc6ZNWc0lg2Rzz+CuOckyRbhrfTlALQbnhm4I9rxwqeyMPVnvOJSkS/dYfi9px0VcIaIjee9wD94VqylzDBdfLeiq+OH7qUXyYMs5eMigSTBLZaclNWZANfrcGFegzh4O61hjweLEjFvQYCVIwg/E/Ivv6uO7GvH+c0VpdAvuyxfoSKu2H1BOkPg8vP/AHp1j4IwRf0muY3Wolx26LLN0CgTGqExml+yhYZ5fOH3bgPHCE+LZdkE2RHms9I8j6kXdAdwYZkVbUqxkdOVg8apOGExKx4EkbiHWUC5b/6gjN3H2VoMA5fm22tJrD7CrYXjkYs3/seFk/Cj4giCxyQ/QLpAqnL+POK3tN9l0XG4WIAZVJdEy7SlQ+hvKCptQMiIHNDsb2Gf6O4bRATFdiDzhIAe6qURKg7RwTKKve77q0wO+zEUuScQyEi2Y7LzIVZJNxrdFBBXPIEbhdaa/rr3XXNmhxkVRJwIS9C21wyzlDvYux1G4+HkQsrdbJZJNO6GPYs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
